### ISSUE TITLE
an SMP kernel needs userland built with :/configure --enable-smp

### ISSUE THREAD

**Issue by mhaberler** [zultron/xenomai-deb#2]
I didnt have a chance to test a --enable-smp built runtime against a non-SMP kernel yet

**Comment by zultron** [comment]
Just rebuilt `xenomai_3.0rc4-1~1jessie.bleeding~1da` source package.  For both `x86` architectures, the default `./configure` args resulted in `checking for SMP support... y`.  Can you describe the problem you're seeing?

**Comment by mhaberler** [comment]
I'm seeing this only on the BB by analogy, not on x86 as the kernel immediately exits
I will try the kernel and libs on an older platform and see what happens

**Comment by zultron** [comment]
Just checked `configure.ac` in the Xenomai source.  This option is enabled by default for `x86` architectures.

This option will be needed once some distro starts shipping packages for non-x86 multi-core targets, like some ARM boards.  The Dovetail Automata repo doesn't ship such architectures, so this feature is already in all binary packages.  I'll accept a PR against this repo in case others are building against this packaging.

Closing issue.

**Comment by mhaberler** [comment]
oops, sorry
